{
  "Topic": {
    "TopicId": "yply8jv6w0kxhpcinowsbq",
    "ForumId": "10",
    "Title": "NPCs or Monsters attacking selves with CombatLib",
    "LastUpdated": "2018-11-15T22:54:34.1984022Z",
    "ReplyCount": 0
  },
  "Posts": [
    {
      "PostId": "33e04a4f-a508-4abc-b7e2-864764ee7fd0",
      "UserId": 385983,
      "Username": "JonQ",
      "AvatarUrl": "https://secure.gravatar.com/avatar/1a5b192120bdcb508202c028b133ebca?d=retro",
      "UserAvatar": null,
      "UserGravatar": null,
      "EditableText": "With CombatLib, any given monster (or NPC) in my game will attack itself at random during various sessions of play instead of attacking the player. I have tried reloading the CombatLib files into my game folder, just to make sure I didn't tweak something I should not have, but even with completely original CombatLib files, it still does this.\r\n\r\nI have isolated the problem by creating a brand new game without interference from any tweaks in my other (actual) game. All I did in this new game (just 3 rooms, 2 monsters, 1 NPC, nothing else at all, no descriptions or anything else) was add the NPCLib and CombatLib. I have the same problem.\r\n\r\nThe problem only occurs if you implement the 'friend' option whereby an NPC can fight alongside the player by using this starting script:\r\n\r\ndo (NpcName, \"settodefend\")\r\n\r\nMy guess is that somehow this 'settodefend' code is not updating lists (attackers or friends) correctly, or in some other way Quest is making the monster or NPC select itself as a target instead of other monsters.  This addition of the 'settodefend' starting script was the lone factor that made monsters or NPCs attack themselves. \r\n\r\nI did try to see if anyone else on the forums had problems like this, and indeed I found an unresolved topic along the same lines back in February:  https://textadventures.co.uk/forum/quest/topic/ppcz9qjyp062hw0wvohvhw/problem-with-followers-in-pixies-combat-lib \r\n\r\nI would love to have NPCs fighting alongside my player. Is this possible?\r\n",
      "EditableFormat": "markdown",
      "HTML": "<p>With CombatLib, any given monster (or NPC) in my game will attack itself at random during various sessions of play instead of attacking the player. I have tried reloading the CombatLib files into my game folder, just to make sure I didn't tweak something I should not have, but even with completely original CombatLib files, it still does this.</p>\n<p>I have isolated the problem by creating a brand new game without interference from any tweaks in my other (actual) game. All I did in this new game (just 3 rooms, 2 monsters, 1 NPC, nothing else at all, no descriptions or anything else) was add the NPCLib and CombatLib. I have the same problem.</p>\n<p>The problem only occurs if you implement the 'friend' option whereby an NPC can fight alongside the player by using this starting script:</p>\n<p>do (NpcName, \"settodefend\")</p>\n<p>My guess is that somehow this 'settodefend' code is not updating lists (attackers or friends) correctly, or in some other way Quest is making the monster or NPC select itself as a target instead of other monsters.  This addition of the 'settodefend' starting script was the lone factor that made monsters or NPCs attack themselves.</p>\n<p>I did try to see if anyone else on the forums had problems like this, and indeed I found an unresolved topic along the same lines back in February:  https://textadventures.co.uk/forum/quest/topic/ppcz9qjyp062hw0wvohvhw/problem-with-followers-in-pixies-combat-lib</p>\n<p>I would love to have NPCs fighting alongside my player. Is this possible?</p>\n\n",
      "PostDate": "2018-11-15T22:54:34.1984022Z",
      "LastEditDate": null,
      "link": null
    }
  ]
}
